name: Release Prod

on:
  push:
    tags:
      - v*.*.*

jobs:
  call-function:
    name: Call function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Dagger
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: 0.18.9
          verb: functions
          workdir: ./etc/workflow-runtime

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - run: "yarn install"
      - run: "./etc/scripts/workflows/release.ts"

      - name: Upload extensions
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: target/release/m*.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
